version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: TrustTrade
      POSTGRES_USER: rajbeer
      POSTGRES_PASSWORD: q1w2e3r4t5y6
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    environment:
      DATABASE_URL: "postgresql://rajbeer:q1w2e3r4t5y6@db:5432/TrustTrade"
    ports:
      - "3500:3500"
    depends_on:
      - db

volumes:
  postgres_data:
