version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: TrustTrade
      POSTGRES_USER: rajbeer
      POSTGRES_PASSWORD: q1w2e3r4t5y6
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: